# Generated by Django 4.1 on 2022-08-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='recorded timestamp')),
                ('temp_C', models.FloatField(default=None, verbose_name='temperature C')),
                ('rel_humidity', models.FloatField(default=None, verbose_name='relative humidity')),
                ('precipitation', models.FloatField(default=None, verbose_name='precipitation')),
            ],
        ),
    ]
